language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: pytest
deploy:
  provider: pypi
  user:
    secure: "doxjHVz+75y9ZBioOOU309ImjyHfDCXNi+3U+lpQBPfbCVWvEsDxg8mvXkPpzxYVdRO0Lwz+JuxSTmYO5TtAR/Z1b1kBggO7gPwHuPsm2PSLZ5zOVPKjtUcLtmH8A8111d2pL6UBUtgr6/UfxZyuEU6CIThdnLyb8lqUC2KeNHdAeWIfrZvXeIc6F8aerwGofRwBwt3SwDqyS07Uy1WjY9i+PqzgxViqYaRM/KT46oYy6R1GRw31KdUxpnHf56+7c0+99P+pyliGwY4TEXvoZ/bf23OGscYLD77ccIx+4jKZIq/0h/H16TPOtPkfSBb1//7tU0QK/VcuIaS4p/5nizwqz9GsPCw3431Jk7NiciTAHucoCvKQZ7/18Q9ciIhb0UcqnKl/tAtryrKKs750y1OlT96blPSL8GoEcK2yl8HbRQug5Cq4M2u4haN2xM3rVunzulo2sQUyNVuo5T/qy4kxbI1I6p7du9naau+6ruZjalpAhPbkWZjED8+ZZtbTVGkUOnRSVwJ83OfGpHDeB3LJYyLBw3U2w5nfVJ303KN76u2BZ29un+VZDC8hdbY3tHLNIiCPjeKb3wl6gNkj2sQY/cGPUFXoXf1BFtus2G+jAEvHJ+Q2asVFW0/kIKPomNPl4UdPlDKsPxTQb7b9dGbTeXPNxA8AyYP/VclUTjE="
  password:
    secure: "xGnmTJN9gDLbpJrucSEiqbxs3Mr5KrGY8Y9RTa28MJDo859zlDbhQGmpKZlGSV8QuBfQ+YSBXNFc59qQEj9owY672QBiJ7mQQBhufRlJnzaoeJ1Wjt+y6SPvpWnGXzL1cm20cdogBXTfhFcYfGDuZWJ/Z4n/LZ8w88j1P6boPgv02CyPNNiQy7J+lYwlE+kamx6U5TIPluOPOyl8kwEGJ4wMJDUTZVJpif/QQL5QrXrOR6M5gYoLjXygAtin+TN6MqiEXy/yv/+uOXywXtNSZwEPOdQpzVSk2t44r/n22NN9H5eJPaE/96YaOembbrEWK8aa5tJYfrlgIJX6TiXNRXgb4XrZu18o0/vJPjfOrI+fQ2psW+nMUW+ZvVLnurHYOaY5QkdxGh57repf/giGSMAClegcsnz46X4HivpZbECjoYFKnvBPSY/KMqm6MnaRNhzaF+IMEtFPCnLeFCobWSXvIbWDq3CZQZpaRY3yqh2Uw5bO3N/LtQoHHX9e9/P26K+m7C4UUtipZtk2stbq6IWokDrOX/2TIWMW7xLX6mso9+XYIyS6+1r2dJereULc10LaVSJ9l6fGx+LowIBhIbC0Y40ikNt8MkvjhDp3Rz3f+GH5lgVUM15nhNbHDqZffWF5H/QY3rDjQOMyN1mJGuixj6mC6Gnu9eht5U19Ix0="
  on:
    all_branches: true
