language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: pytest
deploy:
  provider: pypi
  user:
    secure: PYPI_USERNAME
  password:
    secure: PYPI_PASSWORD
  on:
    all_branches: true
