language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script: pytest
